spring:
  application:
    name: eureka_server
  security:
    basic:
      enabled: true
    user:
      name: ${EUREKA_SECURITY_USERNAME:ms-eureka-server}
      password: ${EUREKA_SECURITY_PASSWORD:002cd034-e604-4084-ab1a-ef49a8f135e6}


server:
  port: 8761


eureka:
  client:
    register-with-eureka: false
    fetch-registry: false