server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://${DATA_BASE_URL:localhost}:3306/order?createDatabaseIfNotExist=true&serverTimezone=UTC
    username: ${DATA_BASE_USERNAME:root}
    password: ${DATA_BASE_PASSWORD:123456}
  flyway:
    locations: classpath:db/migration
  kafka:
    bootstrap-servers: ${KAFKA_URL:localhost}:${KAFKA_PORT:9092}
  cloud:
    stream:
      function:
        definition: appUpdatedEventListener
      bindings:
        appUpdatedEventListener-in-0:
          destination: app.v1.event.app-updated
          group: scheduler