spring:
  application:
    name: order
  datasource:
    url: jdbc:mysql://${DATA_BASE_URL:localhost}:3306/order?createDatabaseIfNotExist=true&serverTimezone=UTC
    username: ${DATA_BASE_USERNAME:root}
    password: ${DATA_BASE_PASSWORD:123456}
  flyway:
    locations: classpath:db/migration
  kafka:
    bootstrap-servers: ${KAFKA_URL:localhost}:${KAFKA_PORT:9092}
  rabbitmq:
    username: ${RABBIT_MQ_USERNAME:rabbitmq}
    password: ${RABBIT_MQ_PASSWORD:rabbitmq}
    host: ${RABBIT_HOST:localhost}
    port: 5672
  cloud:
    stream:
      function:
        definition: appUpdatedEventListener
      bindings:
        appUpdatedEventListener-in-0:
          destination: app.v1.event.app-updated
          group: scheduler

server:
  port: 0

eureka:
  client:
    server-url:
      defaultZone: http://${EUREKA_URL:localhost}:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}


management:
  endpoints:
    web:
      exposure:
        include: '*'
        
logging:
  file:
    name: ./logs/log-order-file.log