version: '3.9'

services:

  eureka-server:
    image: talissonmelo/eureka_server:latest
    ports:
      - 8761:8761
    environment:
    - EUREKA_SECURITY_USERNAME=ms-eureka-server
    - EUREKA_SECURITY_PASSWORD=002cd034-e604-4084-ab1a-ef49a8f135e6
    networks:
      - network

  zookeeper:
    image: confluentinc/cp-zookeeper:5.5.1
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    networks:
      - network
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  broker:
    image: confluentinc/cp-kafka:5.5.1
    hostname: broker
    container_name: broker
    depends_on:
      - zookeeper
    ports:
      - "29092:29092"
      - "9092:9092"
      - "9101:9101"
    networks:
      - network
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_JMX_PORT: 9101

  kafdrop:
    image: obsidiandynamics/kafdrop:3.27.0
    depends_on:
      - broker
    ports:
      - 9000:9000
    networks:
      - network
    environment:
      KAFKA_BROKERCONNECT: broker:29092

  mysql:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    ports:
      - "3306:3306"
    networks:
      - network

  rabbitmq:
    image: rabbitmq:3.7.8-management
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_USER=rabbitmq
      - RABBITMQ_DEFAULT_PASS=rabbitmq
    healthcheck:
      test: [ "CMD", "rabbitmqctl", "status" ]
      interval: 20s
      timeout: 5s
      retries: 10
    networks:
      - network

  keycloak:
    image: quay.io/keycloak/keycloak:23.0.4
    ports:
      - "8081:8080"
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    command: start-dev
    networks:
      - network

  api-gateway:
    image: talissonmelo/api-gateway:latest
    restart: always
    depends_on:
    - eureka-server
    - keycloak
    environment:
      EUREKA_URL: eureka-server
      SECURITY_URL: keycloak
    networks:
      - network

  order:
    image: talissonmelo/order:latest
    restart: always
    depends_on:
    - eureka-server
    - keycloak
    - mysql
    - rabbitmq
    - broker
    - zookeeper
    - kafdrop
    environment:
      DATA_BASE_URL: mysql
      DATA_BASE_USERNAME: root
      DATA_BASE_PASSWORD: 123456
      EUREKA_URL: eureka-server
      KAFKA_PORT: 9092
      RABBIT_HOST: rabbitmq
      RABBIT_MQ_USERNAME: rabbitmq
      RABBIT_MQ_PASSWORD: rabbitmq
    networks:
      - network


  order_payment:
    image: talissonmelo/order_payment:latest
    restart: always
    depends_on:
    - eureka-server
    - keycloak
    - mysql
    - broker
    - zookeeper
    - kafdrop
    environment:
      DATA_BASE_URL: mysql
      DATA_BASE_USERNAME: root
      DATA_BASE_PASSWORD: 123456
      EUREKA_URL: eureka-server
      KAFKA_PORT: 9092
    networks:
      - network
  
  order_report:
    image: talissonmelo/order_report:latest
    restart: always
    depends_on:
    - eureka-server
    - keycloak
    - mysql
    - broker
    - zookeeper
    - kafdrop
    environment:
      DATA_BASE_URL: mysql
      DATA_BASE_USERNAME: root
      DATA_BASE_PASSWORD: 123456
      EUREKA_URL: eureka-server
      KAFKA_PORT: 9092
    networks:
      - network

networks:
  network:
    driver: bridge