server:
  port: 0

spring:
  application:
    name: order-payment
  datasource:
    url: jdbc:mysql://${DATA_BASE_URL:localhost}:3306/order_payment?createDatabaseIfNotExist=true&serverTimezone=UTC
    username: ${DATA_BASE_USERNAME:root}
    password: ${DATA_BASE_PASSWORD:123456}
  flyway:
    locations: classpath:db/migration
  kafka:
    bootstrap-servers: ${KAFKA_URL:localhost}:${KAFKA_PORT:9092}


eureka:
  client:
    server-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}