
server:
  port: 8083

spring:
  datasource:
    url: jdbc:mysql://${DATA_BASE_URL:localhost}:3306/order_report?createDatabaseIfNotExist=true&serverTimezone=UTC
    username: ${DATA_BASE_USERNAME:root}
    password: ${DATA_BASE_PASSWORD:123456}
  flyway:
    locations: classpath:db/migration
  kafka:
    bootstrap-servers: ${KAFKA_URL:localhost}:${KAFKA_PORT:9092}
  rabbitmq:
    username: ${RABBIT_MQ_USERNAME:rabbitmq}
    password: ${RABBIT_MQ_PASSWORD:rabbitmq}
    host: ${RABBIT_HOST:localhost}
    port: 5672
  cloud:
    stream:
      function: 
        definition: appUpdatedSupplier
      bindings:
       appUpdatedSupplier-out-0:
          destination: app.v1.event.app-updated

